# Generated by Django 4.2.7 on 2023-11-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='events.EventInvite', to='events.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='events_attending',
            field=models.ManyToManyField(through='events.EventInvite', to='events.event'),
        ),
    ]
