# Generated by Django 4.2.7 on 2023-11-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_attendees_user_events_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
