# Generated by Django 4.2.7 on 2023-11-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='events.EventInvite', to='events.user'),
        ),
    ]
