# Generated by Django 4.2.7 on 2023-11-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events_attending',
        ),
    ]
